name: Auto commit github

on:
  # Triggers the workflow from 0 through 30 past every hour from 18 through 22
  schedule:
    - cron: "30 17 * * *"

jobs:
  auto_commit:
    name: 'Auto push a commit to my repo'
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create text i love you
      run: echo "I LOVE U <3" >> report.txt
    - name: Commit file
      run: |
          git config --global user.name 'khaitk'
          git config --global user.email 'khaitkdev@gmail.com'
          git add report.txt
          git commit -am "Automated report"
          git push origin develop
